version: '2.22.0-desktop.2'

services:
  dotnetLNSF:
    image: ${DOCKER_REGISTRY-}dotnetlnsf
    build:
      context: .
      dockerfile: .
    ports:
      - "5000:80"
    depends_on:
      - serviceName: "sqlserverLNSF"
  
  sqlserverLNSF:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - "1433:1433"