FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY . .
RUN dotnet publish -c Release

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
# WORKDIR /app
# COPY --from=build /app/bin/Debug/net7.0/publish ./
COPY --from=build /app/bin/Release/net7.0/ ./

# Exponha a porta e configure o ponto de entrada
EXPOSE 5000
ENTRYPOINT ["dotnet", "LNSF.dll"]

# docker build -t lnsfwebapi .